# Generated by Django 6.0.7 on 2026-07-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Định danh duy nhất để gọi trong template, vd: 'about-hero', 'value-1'.", unique=True)),
                ('section', models.CharField(choices=[('about_hero', 'Giới thiệu - Hero'), ('about_vision', 'Giới thiệu - Tầm nhìn'), ('about_mission', 'Giới thiệu - Sứ mệnh'), ('about_value', 'Giới thiệu - Giá trị cốt lõi'), ('contact_info', 'Liên hệ - Thông tin'), ('general', 'Khác')], default='general', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/site_content/')),
                ('icon', models.CharField(blank=True, help_text='Tên icon (vd cho Giá trị cốt lõi), tuỳ chọn.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Contents',
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh chân dung, hiển thị avatar tròn grayscale.', null=True, upload_to='team/avatars/')),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Bỏ chọn để ẩn thành viên khỏi trang Giới thiệu.')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'id'],
            },
        ),
    ]
