# Generated by Django 6.0.7 on 2026-07-22 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Giải thích hiện ra sau khi người dùng chọn đáp án.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DigitalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('map_type', models.CharField(choices=[('embed', 'Nhúng iframe'), ('image', 'Ảnh tĩnh (lightbox)'), ('geojson', 'GeoJSON + Leaflet')], default='embed', max_length=20)),
                ('embed_url', models.URLField(blank=True, help_text="Dùng khi map_type = 'embed'.")),
                ('image', models.ImageField(blank=True, help_text="Dùng khi map_type = 'image'.", null=True, upload_to='maps/images/')),
                ('geojson_file', models.FileField(blank=True, help_text="Dùng khi map_type = 'geojson' (load bằng Leaflet.js).", null=True, upload_to='maps/geojson/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='timeline.lesson')),
            ],
            options={
                'verbose_name': 'Digital Map',
                'verbose_name_plural': 'Digital Maps',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='timeline.lesson')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='showcase.gallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField(blank=True, help_text='Link Youtube (hoặc nhúng khác) — ưu tiên nếu có.')),
                ('video_file', models.FileField(blank=True, help_text='Dùng nếu không có video_url (upload file video trực tiếp).', null=True, upload_to='lessons/videos/')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='timeline.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Video',
                'verbose_name_plural': 'Lesson Videos',
            },
        ),
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='showcase.digitalmap')),
            ],
            options={
                'verbose_name': 'Map Marker',
                'verbose_name_plural': 'Map Markers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='showcase.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Choice',
                'verbose_name_plural': 'Quiz Choices',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='timeline.lesson')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='showcase.quizshowcase'),
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='worksheets/previews/')),
                ('file', models.FileField(upload_to='worksheets/files/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='timeline.lesson')),
            ],
            options={
                'verbose_name': 'Worksheet',
                'verbose_name_plural': 'Worksheets',
                'ordering': ['order', 'id'],
            },
        ),
    ]
