"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

---------------------------------------------------------------------------
Task 5.3 (Deploy) — file này đọc cấu hình qua BIẾN MÔI TRƯỜNG để dùng
chung được cho cả dev (chạy `runserver` không cần set gì thêm — mọi biến
đều có giá trị mặc định an toàn cho local) và production (Render — xem
`DEPLOY.md`). Không có biến môi trường nào là bắt buộc để chạy dev.
---------------------------------------------------------------------------
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    """Đọc biến môi trường dạng boolean ('True'/'False'/'1'/'0'/'yes'/'no')."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=None):
    """Đọc biến môi trường dạng danh sách, phân tách bằng dấu phẩy."""
    value = os.environ.get(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
# Local dev: dùng key mặc định bên dưới. Production: BẮT BUỘC set
# DJANGO_SECRET_KEY qua biến môi trường (xem DEPLOY.md) — không commit
# secret key thật của production vào file này.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-c77*e!vxp10!yimxx3&!m$l92erc-y1--^4^_dqy2yduz2or@i',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Mặc định True để không phá quy trình dev hiện tại; production set
# DJANGO_DEBUG=False qua biến môi trường (bắt buộc, xem DEPLOY.md).
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

# Local dev không cần set gì (Django tự cho phép localhost/127.0.0.1 khi
# DEBUG=True). Production: set DJANGO_ALLOWED_HOSTS='ten-app.onrender.com'
# (phân tách bằng dấu phẩy nếu có nhiều domain/tên miền riêng).
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', default=[])

# Cần cho CSRF khi chạy sau HTTPS reverse proxy (Render, Railway, ...).
# Production set DJANGO_CSRF_TRUSTED_ORIGINS='https://ten-app.onrender.com'.
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'timeline',
    'showcase',
    'pages',
]

# django-storages chỉ thật sự cần khi bật S3 cho media (xem mục "Static &
# Media files" bên dưới) — thêm có điều kiện để dev không cần cấu hình gì.
USE_S3_MEDIA = _env_bool('USE_S3_MEDIA', default=False)
if USE_S3_MEDIA:
    INSTALLED_APPS += ['storages']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise phục vụ static file trực tiếp từ Django (không cần Nginx
    # riêng) — phải đặt ngay sau SecurityMiddleware, trước mọi middleware
    # khác. Không ảnh hưởng gì khi DEBUG=True (dev vẫn dùng runserver như cũ).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Dev (không set DATABASE_URL): dùng sqlite3 như cũ, không đổi gì.
# Production (Render): set DATABASE_URL='postgres://...' (Render tự cấp
# khi tạo Postgres instance, dán vào Environment Variables — xem DEPLOY.md).

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded content: cover images, worksheets, gallery images, ...)
#
# QUAN TRỌNG (đọc trước khi deploy): Render/Railway/PythonAnywhere free tier
# đều dùng ổ đĩa TẠM (ephemeral) — file upload qua /admin/ (media/) sẽ MẤT
# mỗi lần redeploy nếu để lưu trên đĩa container. Có 2 lựa chọn:
#   1) Chấp nhận giới hạn này cho bản demo (dùng seed_demo_data để có ảnh
#      ngay sau mỗi lần deploy, không cần ai upload tay) — mặc định của
#      cấu hình dưới đây (USE_S3_MEDIA=False).
#   2) Bật lưu media lên Amazon S3 (bền vững qua các lần deploy) — set
#      USE_S3_MEDIA=True + AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/
#      AWS_STORAGE_BUCKET_NAME/AWS_S3_REGION_NAME qua biến môi trường,
#      xem hướng dẫn tạo bucket trong DEPLOY.md.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # CompressedManifestStaticFilesStorage: nén + đặt tên file theo hash
        # nội dung (cache-busting tự động), khuyến nghị chuẩn của Whitenoise
        # cho production. Dev (DEBUG=True) vẫn phục vụ static qua
        # STATICFILES_DIRS như cũ (xem config/urls.py), không bị ảnh hưởng.
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if USE_S3_MEDIA:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'ap-southeast-1')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or (
        f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
        if AWS_STORAGE_BUCKET_NAME else None
    )
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_LOCATION = 'media'

    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    }
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

# WhiteNoise: nén trước (gzip/brotli) và cache dài hạn cho static file.
WHITENOISE_MAX_AGE = 31536000  # 1 năm — an toàn vì tên file đã có hash

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Bảo mật production (Task 5.3)
# Chỉ bật khi DEBUG=False để không ảnh hưởng gì tới quy trình dev hiện tại
# (chạy http://127.0.0.1:8000 bình thường, không bị ép chuyển HTTPS).
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', default=True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 7 ngày, tăng dần sau khi ổn định
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
